[package]
name = "rovers"
version = "0.1.0"
authors = ["kollch"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.25.3"
statrs = "0.13.0"
